In [175]:
import pandas as pd
import csv

### Extraindo os voos de SBRF(Recife-Guararapes) para SBSP(São Paulo-Congonhas)

A partir da da base de dados da Anac disponíveis no endereço: https://sistemas.anac.gov.br/sas/downloads/view/frmDownload.aspx
Consulta realizada no dia 26/10/2022.

PS: Os dados brutos não estão contigos no GitHub devido a tamanho da base de dados.

In [ ]:
# Gerando uma lista com os nomes dos arquivos CSV.
# O resultado é uma lista de aquivos com a seguinte caracteristica:
# lista_de_arquivos = ['201708.CSV','201709.CSV']

dicionario = {'2017': ['08','09','10','11','12'], 
              '2018': ['01','02','03','04','05','06','07','08','09','10','11','12'],
              '2019': ['01','02','03','04','05','06','07','08','09','10','11','12'],
              '2020': ['01','02','03','04','05','06','07','08','09','10','11','12'],
              '2021': ['01','02','03','04','05','06','07','08','09','10','11','12'],
              '2022': ['01','02','03','04','05','06','07']
             }
lista_de_arquivos = []
sbrf_sbsp = pd.DataFrame(columns=['ANO','MES','EMPRESA','ORIGEM','DESTINO','TARIFA','ASSENTOS'])
for k, l in dicionario.items():
    for v in range(len(l)):
        lista_de_arquivos.append(f'{k}{l[v]}.CSV')

In [177]:
# Gerando um novo Data Frame apenas com voos de SBRF para SBSP a partir da lista com os nomes dos arquivos.

for cont in range(len(lista_de_arquivos)):
    try:
        df_temporario = pd.read_csv(lista_de_arquivos[cont], sep=';')
        df_temporario = df_temporario.loc[(df_temporario.ORIGEM == 'SBRF') & (df_temporario.DESTINO == 'SBSP')]
        sbrf_sbsp = pd.concat([sbrf_sbsp, df_temporario], ignore_index=True)
    except UnicodeDecodeError: # Resolvendo o problema dos arquivos com cabeçalho diferente, erro UTF-8.
        lista_csv = []
        with open(lista_de_arquivos[cont], "r") as arq:
            arq_csv = csv.reader(arq, delimiter=";")
            for i, linha in enumerate(arq_csv):
                if i > 0:
                    lista_csv.append(linha)
        df_temporario = pd.DataFrame(lista_csv, columns = ['ANO','MES','EMPRESA','ORIGEM','DESTINO','TARIFA','ASSENTOS'])
        df_temporario = df_temporario.loc[(df_temporario.ORIGEM == 'SBRF') & (df_temporario.DESTINO == 'SBSP')]
        sbrf_sbsp = pd.concat([sbrf_sbsp, df_temporario], ignore_index=True)

In [178]:
sbrf_sbsp

        ANO MES EMPRESA ORIGEM DESTINO  TARIFA ASSENTOS
0      2017   8     AZU   SBRF    SBSP   630,9        1
1      2017   8     AZU   SBRF    SBSP  937,46        1
2      2017   8     AZU   SBRF    SBSP  690,71        1
3      2017   8     AZU   SBRF    SBSP  319,51        1
4      2017   8     AZU   SBRF    SBSP   399,4        2
...     ...  ..     ...    ...     ...     ...      ...
41167  2022   7     TAM   SBRF    SBSP  857,07        1
41168  2022   7     TAM   SBRF    SBSP    584,        1
41169  2022   7     TAM   SBRF    SBSP  1124,9        2
41170  2022   7     TAM   SBRF    SBSP    961,        1
41171  2022   7     TAM   SBRF    SBSP  1049,9        2

[41172 rows x 7 columns]

In [179]:
sbrf_sbsp.to_csv("flights_sbrf_to_sbsp.csv", index=False)